### ISSUE TITLE
Raft pattern angles

### ISSUE THREAD

**Issue by wfcook** [slic3r/Slic3r#3001]
I've noticed a couple of things about rafts that are less than ideal:

(1) The first two layers of the raft are printed at the same pattern angle, which results in the first layer (thicker extrusion) not properly supporting the second layer (thinner).

(2) The first interface layer is printed at the same pattern angle as the first raft angle, no matter what angle the prior raft layer was printed at. Again, this results in improperly supported interface material unless an odd number of non-interface raft layers is used.

(3) All interface layers are printed at the same angle. This is not necessarily a problem, but not what I expected and I would think it would be better if they alternated like the other layers. What it the reason for this?

Thanks,
Bill Cook _/)_

**Comment by GregoryNoel** [comment]
I experienced a problem with interface layers in the same direction. The first layer was not perfectly sticking to the support material (5mm height) and then the second interface layer was imperfect.
The first layer above the support material is in fact very poor in quality because not sticking well on the irregular height of interface layer -> Very poor finish on this object layer.

**Comment by GregoryNoel** [comment]
I'm not expert in perl, but I've tried changing angles. I add 2 lines in SupportMaterial.pm.
Interface layers are now each time rotated.

If someone want to try, to enhance and integrate it, feel free.

![interface_angle_0](https://cloud.githubusercontent.com/assets/13418536/9427669/b468e020-4989-11e5-8fb4-53c136495242.jpg)
![interface_angle_1](https://cloud.githubusercontent.com/assets/13418536/9427672/b49ed590-4989-11e5-8922-1ea75cdf8303.jpg)
![interface_angle_2](https://cloud.githubusercontent.com/assets/13418536/9427670/b492e6e0-4989-11e5-8436-2b3a26acfc0e.jpg)
![interface_angle_3](https://cloud.githubusercontent.com/assets/13418536/9427671/b498ab16-4989-11e5-83cd-eefee63940cc.jpg)

**Comment by a4jp-com** [comment]
I can't understand what is happening here. My layers are working and each layer is rotated 90 degrees from the last so everything seems to work. How do you make the supports? Do you have a simple test file? Maybe a cube with supports on the side or something.

![screen shot 08-24-15 at 03 06 pm](https://cloud.githubusercontent.com/assets/9621044/9433755/c679e104-4a71-11e5-9914-ccf2642ca0f0.JPG)
![screen shot 08-24-15 at 03 05 pm 002](https://cloud.githubusercontent.com/assets/9621044/9433756/c67e9d0c-4a71-11e5-9764-a6b5023f694e.JPG)
![screen shot 08-24-15 at 03 05 pm 001](https://cloud.githubusercontent.com/assets/9621044/9433757/c682fa82-4a71-11e5-81e1-caa4f9c38805.JPG)

**Comment by wfcook** [comment]
The issue is only with rafts and interface layers

**Comment by a4jp-com** [comment]
If I go to printer settings > support material > raft layers and type in a value like 4 I can see the layers don't get rotated as well. Can you fix this @alexrj ?

I'll include some pictures below.
-------------------------

I guess the first layer is being smooshed down so the lines are bigger. This can probably be fixed in the printer settings > advance settings area. Make the first layer the same size as the other layers to fix the problem. After that you couls try adjusting the z-depth in printer settings > size and coordinates > z offset

The other problem of spacing and heat/surface bubbling are probably fixable but you need to upload your config file to get help there. File > export config.

--------------

![screen shot 08-25-15 at 09 10 am](https://cloud.githubusercontent.com/assets/9621044/9455724/340de41c-4b09-11e5-9bfc-acdbe9ddcc66.JPG)
![screen shot 08-25-15 at 09 09 am 004](https://cloud.githubusercontent.com/assets/9621044/9455726/340f8d8a-4b09-11e5-879b-d91cd582021a.JPG)
![screen shot 08-25-15 at 09 09 am 003](https://cloud.githubusercontent.com/assets/9621044/9455727/340feb22-4b09-11e5-8a44-bda7ce7c9ed9.JPG)
![screen shot 08-25-15 at 09 09 am 002](https://cloud.githubusercontent.com/assets/9621044/9455725/340f1e68-4b09-11e5-861e-2a7430b0f0e7.JPG)
![screen shot 08-25-15 at 09 09 am 001](https://cloud.githubusercontent.com/assets/9621044/9455728/34129c5a-4b09-11e5-8f0b-3b091ed0439e.JPG)
![screen shot 08-25-15 at 09 09 am](https://cloud.githubusercontent.com/assets/9621044/9455729/3414513a-4b09-11e5-8eb6-d054c886a016.JPG)

**Comment by koghe** [comment]
hi i asked almost the same question to alexrj some time ago, raft rise the object and it add supports
(https://github.com/alexrj/Slic3r/issues/1323#issuecomment-21620753 )

+++1 to have a alternate angle for raft like the old skeinforge

**Comment by dn63** [comment]
Opened pull request #4334 with code changes suggested by @GregoryNoel (with minor edits).

**Comment by lordofhyphens** [comment]
I've accepted the PR; we'll see how it behaves (and if anyone complains about the behavior :) )

Thank you @dn63
