### ISSUE TITLE
build for 32 bit linux?

### ISSUE THREAD

**Issue by aledthom** [slic3r/Slic3r#4609]
is there a build for v1.3.0 on 32 bit i86? download page only has up to v1.2.9 for linux . thanks

**Comment by lordofhyphens** [comment]
No, we don't provide 32bit Linux builds.it is sufficiently painful to provide such builds on Linux for me (and 32-bit only hardware so old) that I decided to spend my time on more productive endeavors than fighting the build server.

Perhaps when the C++ port is completed.

Since you are on Linux, build from source.
