### ISSUE TITLE
External perimeters not given adequate detail

### ISSUE THREAD

**Issue by VanessaE** [slic3r/Slic3r#4640]
**Describe the bug**

This is Slic3r commit 21eb603cc16946b14e77d3c10cbee2f1163503c6 plus @supermerill's thin wall improvements PR (I'm at commit ca9f3f7e29662c25a0bd5c3ed00232ea8ed68d2a of that).

Slic3r's discarding small features in the model instead of trying to recreate them.  Consider the nameplate on the back of a Benchy:

![screenshot_2018-12-09_01-16-45-2](https://user-images.githubusercontent.com/1733537/49694046-5feb1f00-fb50-11e8-87ed-80990cc56d92.png)

0.4 mm nozzle, 0.4 mm line width, 0.08 mm layer height (config: [config-20181209.ini.zip](https://github.com/slic3r/Slic3r/files/2660290/config-20181209.ini.zip) ).

Compare to this photo I found on Hackaday.  While the image and print quality are mediocre, it clearly shows all of the lettering's individual strokes.  This was apparently also printed with a 0.4 mm nozzle, sliced with Cura (not sure about the layer height, but it looks to be about 0.1 mm).

![benchyback](https://user-images.githubusercontent.com/1733537/49694153-42b75000-fb52-11e8-8f80-33e9c1858f24.jpg)

(rotated, cropped, resized, and I painted-out a blob that was in the middle of the plate, for easier visual comparison; source:  https://hackaday.com/2016/08/30/review-monoprice-maker-ultimate-3d-printer/ ).

**Comment by supermerill** [comment]
for the  '#' : the thin area between the two '/' is too small for a 0.4 nozzle to do a U.

But there should be an extrusion between 3,D,b

If you disable the thin_wall option, you can show it.

The "culprit" is done at perimetergenerator.cpp l85 vs l97. I didn't change it (i just added a little post-process for thin wall to relax the algo a bit if it creates too much ares).

What  i understand : If no thin wall, it lay every perimeter the best way possible. If thin wall, it exclude areas that can be too thin for 2 perimeters (you can se it, when 2 perimeter are almost one over another -> overextrusion), and pray for the thin walls to extrude these thin area. The problem is: sometimes, these areas are too tiny.


I will try something.

**Comment by VanessaE** [comment]
This is one of those situations where Cura, for example, would probably do those overlapped perimeters I mentioned.

**Comment by VanessaE** [comment]
Looking much better with the latest updates on the thin walls PR (commit 44e7ec855e1706fe1af6dddaff5835e018d0b69d):

![screenshot_2018-12-21_03-11-18](https://user-images.githubusercontent.com/1733537/50331836-1e526080-04ce-11e9-8190-1b989564c5a6.png)
