### ISSUE TITLE
customized colors in colorpint preview

### ISSUE THREAD

**Issue by wnc2** [slic3r/Slic3r#4657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
i wish to set custom colors in colorprint preview to have a more realistic render

![schermata 2018-12-29 alle 16 17 04](https://user-images.githubusercontent.com/43959480/50539979-8d444f00-0b89-11e9-83b2-2b4d6658bdd8.jpg)

**Additional context**

**Comment by lordofhyphens** [comment]
Already there. View->"Color toolpaths by filament"

**Comment by lordofhyphens** [comment]
Also, this isn't Prusa3d slic3r issue tracker.

**Comment by lordofhyphens** [comment]
@bubnikv I've put the notice and a link to your tracker in the default template in big text to hopefully catch more of these. 

@wnc2 When moving to the separate feature and bug report templates, I forgot to add the notice (that people only read 15% of the time) to not report Prusa3D specific issues here. I've fixed that.

**Comment by wnc2** [comment]
Tried to be collaborative showing 2 feature request and a bug, I though slic3r and PU version were the same family

Regards

--
WNC2 - World Nutrition Center 2 - Integratori per lo sport
ONLINE STORE: www.wnc2.biz - Tel. 0185-599135
Num. Verde: 800-134727 (da rete fissa) - SKYPE: wnc2.biz
Il 30 dic 2018, 18:00 +0100, Joseph Lenox <notifications@github.com>, ha scritto:

**Comment by lordofhyphens** [comment]
This feature request looks like it is already what you want, the bug needs to be reproducible on our code (prusa fork has diverged a lot to support their printers first and foremost).

**Comment by lordofhyphens** [comment]
And the other feature request (regarding plater window visibility) is already done in Slic3r (just change a setting in Preferences to use dialogs instead of tabs and turn background processing on).

As far as inapplicable issues go, these weren't bad. I have seen people open "pull requests" from prusa3d fork to us and make a bug report against prusa3d!

Obviously if a bug is reproducible on a build from dl.slic3r.org, then I do want to hear about it. If it isn't, then there is nothing I can do but point you at the right place and close the issue here.
